### ISSUE TITLE
Build failure on windows-gnu

### ISSUE THREAD

**Issue by mitsuhiko** [alexcrichton/jobserver-rs#4]
Not sure if this is the right place, but uchardet-sys fails on windows-gnu at the moment on my fork with this error:

```
-- Build files have been written to: C:/projects/rust-uchardet/target/debug/build/uchardet-sys-f767bae7b802ab5d/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
--- stderr
make: *** internal error: invalid --jobserver-auth string '__rust_jobserver_semaphore_2679511779'.  Stop.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2
build script failed, must exit now', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.27\src\lib.rs:627:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Presumably it eventually runs into this check: https://github.com/jaakristioja/make/blob/6371bb5dcef4ab5de16a1fddb2ae21c44588c6b8/posixos.c#L85

**Comment by mitsuhiko** [comment]
This clearly expects a numeric value and it gets a string. The value that is passed by the time the code parses it is this one:

```
CARGO_MAKEFLAGS=--jobserver-fds=__rust_jobserver_semaphore_3354176947 --jobserver-auth=__rust_jobserver_semaphore_3354176947
```

This seems wrong.

**Comment by mitsuhiko** [comment]
So the issue comes from here: https://github.com/alexcrichton/jobserver-rs/blob/3d89d895c62fbfe80c90b50e204acb6a5fafff4d/src/lib.rs#L857

It assumes that the `string_arg` on non unix targets works which clearly is incorrect for windows-gnu. Not even sure what the fix here is.

**Comment by mitsuhiko** [comment]
I guess the docs hint this:

> There appear to be two implementations of make on Windows. On MSYS2 one typically comes as mingw32-make and the other as make itself. I'm not personally too familiar with what's going on here, but for jobserver-related information the mingw32-make implementation uses Windows semaphores whereas the make program does not. The make program appears to use file descriptors and I'm not really sure how it works, so this crate is not compatible with make on Windows. It is, however, compatible with mingw32-make.

**Comment by alexcrichton** [comment]
I believe this is https://github.com/alexcrichton/cmake-rs/commit/a02d3b47077aa0157bb89177b9ea52db277bc952, not this library, so closing.

**Comment by mitsuhiko** [comment]
@alexcrichton not saying you are wrong but are you sure? Because the bad value already shows up in the `CARGO_MAKEFLAGS` var when printed in the main build.rs. Which means that this is set from cargo.  Going to try this now though. Cmake is involved here for sure.

**Comment by alexcrichton** [comment]
Yep! I've run into this tons of times
